name: Semantic Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'export PATH="/home/runner/.bun/bin:$PATH"' >> $GITHUB_ENV


      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
